'use client'
import { createContext, useContext, useState } from 'react'

type Language = 'en' | 'ar' | 'hi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    signIn: 'Sign In',
    startNow: 'Start Now',
    freeTrialButton: 'Free 30-Day Trial',
    watchDemo: 'Watch Demo',
    advancedPOS: 'Advanced POS Terminals',
    mobileApp: 'Mobile App',
    instantProcessing: 'Instant Processing',
    copyright: '© 2026 DSR Pro. All rights reserved by TechRover',
    signInTitle: 'Sign in to your account',
    signUpTitle: 'Create your account',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    companyName: 'Company Name',
    phoneNumber: 'Phone Number',
    role: 'Role',
    agent: 'Agent',
    vendor: 'Vendor',
    signingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    signUp: 'Sign up',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    dashboard: 'Dashboard',
    vendors: 'Vendors',
    receipts: 'Receipts',
    payments: 'Payments',
    reports: 'Reports',
    settings: 'Settings',
    signOut: 'Sign out',
    receiptPaymentManagement: 'Receipt & Payment Management',
    superAdmin: 'Super Admin',
    name: 'Name',
    contact: 'Contact',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    overviewSystem: 'Overview of your receipt and payment management system',
    totalReceiptsToday: 'Total Receipts (Today)',
    totalPaymentsToday: 'Total Payments (Today)',
    pendingPayments: 'Pending Payments',
    activeVendors: 'Active Vendors',
    monthlyOverview: 'Monthly Overview',
    recentActivity: 'Recent Activity',
    manageVendors: 'Manage your vendors and their information',
    addVendor: 'Add Vendor',
    searchVendors: 'Search vendors...',
    manageReceipts: 'Manage all your receipt entries',
    addReceipt: 'Add Receipt',
    searchReceipts: 'Search receipts...',
    receiptNumber: 'Receipt Number',
    amount: 'Amount',
    date: 'Date',
    vendorName: 'Vendor',
    description: 'Description',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    managePayments: 'Manage all your payment transactions',
    addPayment: 'Add Payment',
    searchPayments: 'Search payments...',
    paymentId: 'Payment ID',
    paymentMethod: 'Payment Method',
    transactionDate: 'Transaction Date',
    pending: 'Pending',
    completed: 'Completed',
    failed: 'Failed',
    viewReports: 'View comprehensive reports and analytics',
    generateReport: 'Generate Report',
    salesReport: 'Sales Report',
    paymentReport: 'Payment Report',
    vendorReport: 'Vendor Report',
    monthlyReport: 'Monthly Report',
    yearlyReport: 'Yearly Report',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    systemSettings: 'Configure your system preferences',
    profile: 'Profile',
    notifications: 'Notifications',
    security: 'Security',
    language: 'Language',
    theme: 'Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    save: 'Save',
    cancel: 'Cancel',
    update: 'Update',
    confirm: 'Confirm',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data available',
    total: 'Total',
    filter: 'Filter',
    sort: 'Sort',
    refresh: 'Refresh'
  },
  ar: {
    signIn: 'تسجيل الدخول',
    startNow: 'ابدأ الآن',
    freeTrialButton: 'جرب مجاناً لمدة 30 يوم',
    watchDemo: 'شاهد العرض التوضيحي',
    advancedPOS: 'نقاط البيع المتقدمة',
    mobileApp: 'تطبيق الجوال',
    instantProcessing: 'معالجة فورية',
    copyright: '© 2026 DSR Pro. جميع الحقوق محفوظة بواسطة TechRover',
    signInTitle: 'تسجيل الدخول إلى حسابك',
    signUpTitle: 'إنشاء حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    companyName: 'اسم الشركة',
    phoneNumber: 'رقم الهاتف',
    role: 'الدور',
    agent: 'وكيل',
    vendor: 'مورد',
    signingIn: 'جاري تسجيل الدخول...',
    creatingAccount: 'جاري إنشاء الحساب...',
    signUp: 'إنشاء حساب',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dashboard: 'لوحة التحكم',
    vendors: 'الموردين',
    receipts: 'الإيصالات',
    payments: 'المدفوعات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
    receiptPaymentManagement: 'إدارة الإيصالات والمدفوعات',
    superAdmin: 'مدير عام',
    name: 'الاسم',
    contact: 'الاتصال',
    status: 'الحالة',
    actions: 'الإجراءات',
    active: 'نشط',
    inactive: 'غير نشط',
    overviewSystem: 'نظرة عامة على نظام إدارة الإيصالات والمدفوعات',
    totalReceiptsToday: 'إجمالي الإيصالات (اليوم)',
    totalPaymentsToday: 'إجمالي المدفوعات (اليوم)',
    pendingPayments: 'المدفوعات المعلقة',
    activeVendors: 'الموردين النشطين',
    monthlyOverview: 'نظرة عامة شهرية',
    recentActivity: 'النشاط الأخير',
    manageVendors: 'إدارة الموردين ومعلوماتهم',
    addVendor: 'إضافة مورد',
    searchVendors: 'البحث عن الموردين...',
    manageReceipts: 'إدارة جميع إدخالات الإيصالات',
    addReceipt: 'إضافة إيصال',
    searchReceipts: 'البحث في الإيصالات...',
    receiptNumber: 'رقم الإيصال',
    amount: 'المبلغ',
    date: 'التاريخ',
    vendorName: 'المورد',
    description: 'الوصف',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    managePayments: 'إدارة جميع معاملات الدفع',
    addPayment: 'إضافة دفعة',
    searchPayments: 'البحث في المدفوعات...',
    paymentId: 'معرف الدفع',
    paymentMethod: 'طريقة الدفع',
    transactionDate: 'تاريخ المعاملة',
    pending: 'معلق',
    completed: 'مكتمل',
    failed: 'فشل',
    viewReports: 'عرض التقارير والتحليلات الشاملة',
    generateReport: 'إنشاء تقرير',
    salesReport: 'تقرير المبيعات',
    paymentReport: 'تقرير المدفوعات',
    vendorReport: 'تقرير الموردين',
    monthlyReport: 'التقرير الشهري',
    yearlyReport: 'التقرير السنوي',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    systemSettings: 'تكوين تفضيلات النظام',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    security: 'الأمان',
    language: 'اللغة',
    theme: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    save: 'حفظ',
    cancel: 'إلغاء',
    update: 'تحديث',
    confirm: 'تأكيد',
    close: 'إغلاق',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات متاحة',
    total: 'المجموع',
    filter: 'تصفية',
    sort: 'ترتيب',
    refresh: 'تحديث'
  },
  hi: {
    signIn: 'साइन इन',
    startNow: 'शुरू करें',
    freeTrialButton: '30 दिन मुफ्त ट्रायल',
    watchDemo: 'डेमो देखें',
    advancedPOS: 'उन्नत POS टर्मिनल',
    mobileApp: 'मोबाइल ऐप',
    instantProcessing: 'तत्काल प्रसंस्करण',
    copyright: '© 2026 DSR Pro. सभी अधिकार TechRover द्वारा सुरक्षित',
    signInTitle: 'अपने खाते में साइन इन करें',
    signUpTitle: 'अपना खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    companyName: 'कंपनी का नाम',
    phoneNumber: 'फोन नंबर',
    role: 'भूमिका',
    agent: 'एजेंट',
    vendor: 'विक्रेता',
    signingIn: 'साइन इन हो रहा है...',
    creatingAccount: 'खाता बनाया जा रहा है...',
    signUp: 'साइन अप',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    dashboard: 'डैशबोर्ड',
    vendors: 'विक्रेता',
    receipts: 'रसीदें',
    payments: 'भुगतान',
    reports: 'रिपोर्ट्स',
    settings: 'सेटिंग्स',
    signOut: 'साइन आउट',
    receiptPaymentManagement: 'रसीद और भुगतान प्रबंधन',
    superAdmin: 'सुपर एडमिन',
    name: 'नाम',
    contact: 'संपर्क',
    status: 'स्थिति',
    actions: 'कार्य',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    overviewSystem: 'आपकी रसीद और भुगतान प्रबंधन प्रणाली का अवलोकन',
    totalReceiptsToday: 'कुल रसीदें (आज)',
    totalPaymentsToday: 'कुल भुगतान (आज)',
    pendingPayments: 'लंबित भुगतान',
    activeVendors: 'सक्रिय विक्रेता',
    monthlyOverview: 'मासिक अवलोकन',
    recentActivity: 'हाल की गतिविधि',
    manageVendors: 'अपने विक्रेताओं और उनकी जानकारी का प्रबंधन करें',
    addVendor: 'विक्रेता जोड़ें',
    searchVendors: 'विक्रेता खोजें...',
    manageReceipts: 'अपनी सभी रसीद प्रविष्टियों का प्रबंधन करें',
    addReceipt: 'रसीद जोड़ें',
    searchReceipts: 'रसीदें खोजें...',
    receiptNumber: 'रसीद संख्या',
    amount: 'राशि',
    date: 'दिनांक',
    vendorName: 'विक्रेता',
    description: 'विवरण',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    managePayments: 'अपने सभी भुगतान लेनदेन का प्रबंधन करें',
    addPayment: 'भुगतान जोड़ें',
    searchPayments: 'भुगतान खोजें...',
    paymentId: 'भुगतान ID',
    paymentMethod: 'भुगतान विधि',
    transactionDate: 'लेनदेन दिनांक',
    pending: 'लंबित',
    completed: 'पूर्ण',
    failed: 'असफल',
    viewReports: 'व्यापक रिपोर्ट और विश्लेषण देखें',
    generateReport: 'रिपोर्ट जेनरेट करें',
    salesReport: 'बिक्री रिपोर्ट',
    paymentReport: 'भुगतान रिपोर्ट',
    vendorReport: 'विक्रेता रिपोर्ट',
    monthlyReport: 'मासिक रिपोर्ट',
    yearlyReport: 'वार्षिक रिपोर्ट',
    exportPDF: 'PDF निर्यात करें',
    exportExcel: 'Excel निर्यात करें',
    systemSettings: 'अपनी सिस्टम प्राथमिकताएं कॉन्फ़िगर करें',
    profile: 'प्रोफाइल',
    notifications: 'सूचनाएं',
    security: 'सुरक्षा',
    language: 'भाषा',
    theme: 'थीम',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    update: 'अपडेट करें',
    confirm: 'पुष्टि करें',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    total: 'कुल',
    filter: 'फिल्टर',
    sort: 'सॉर्ट करें',
    refresh: 'रिफ्रेश करें'
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}