'use client'
import { createContext, useContext, useState } from 'react'

type Language = 'en' | 'ar' | 'hi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    signIn: 'Sign In',
    startNow: 'Start Now',
    freeTrialButton: 'Free 30-Day Trial',
    watchDemo: 'Watch Demo',
    advancedPOS: 'Advanced POS Terminals',
    mobileApp: 'Mobile App',
    instantProcessing: 'Instant Processing',
    copyright: '© 2026 DSR Info. All rights reserved by TechRover',
    signInTitle: 'Sign in to your account',
    signUpTitle: 'Create your account',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    companyName: 'Company Name',
    phoneNumber: 'Phone Number',
    role: 'Role',
    agent: 'Agent',
    signingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    signUp: 'Sign up',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    dashboard: 'Dashboard',
    receipts: 'Receipts',
    payments: 'Payments',
    reports: 'Reports',
    settings: 'Settings',
    signOut: 'Sign out',
    receiptPaymentManagement: 'Receipt & Payment Management',
    superAdmin: 'Super Admin',
    name: 'Name',
    contact: 'Contact',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    overviewSystem: 'Overview of your receipt and payment management system',
    totalReceiptsToday: 'Total Receipts (Today)',
    totalPaymentsToday: 'Total Payments (Today)',
    pendingPayments: 'Pending Payments',
    activeVendors: 'Active Agents',
    monthlyOverview: 'Monthly Overview',
    recentActivity: 'Recent Activity',
    manageReceipts: 'Manage all your receipt entries',
    addReceipt: 'Add Receipt',
    searchReceipts: 'Search receipts...',
    receiptNumber: 'Receipt Number',
    amount: 'Amount',
    date: 'Date',
    vendorName: 'Agent',
    description: 'Description',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    managePayments: 'Manage all your payment transactions',
    addPayment: 'Add Payment',
    searchPayments: 'Search payments...',
    paymentId: 'Batch ID',
    transactionId: 'Batch ID',
    batchId: 'Batch ID',
    paymentMethod: 'Payment Method',
    transactionDate: 'Transaction Date',
    pending: 'Pending',
    completed: 'Completed',
    failed: 'Failed',
    viewReports: 'View comprehensive reports and analytics',
    generateReport: 'Generate Report',
    salesReport: 'Sales Report',
    paymentReport: 'Payment Report',
    vendorReport: 'Agent Report',    monthlyReport: 'Monthly Report',
    yearlyReport: 'Yearly Report',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    systemSettings: 'Configure your system preferences',
    profile: 'Profile',
    notifications: 'Notifications',
    security: 'Security',
    language: 'Language',
    theme: 'Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    save: 'Save',
    cancel: 'Cancel',
    update: 'Update',
    confirm: 'Confirm',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data available',
    total: 'Total',
    filter: 'Filter',
    sort: 'Sort',
    noPaymentsFound: 'No Payments Found',
    noPaymentsDescription: 'You haven\'t created any payments yet. Start by adding your first payment.',
    addFirstPayment: 'Add First Payment',
    paymentsReport: 'Payments Report',
    getStarted: 'Get Started',
    dsrPro: 'DSR Info',
    dubaiPremierPOS: 'Dubai\'s Premier POS System',
    advancedPOSTitle: 'Advanced POS System for Dubai',
    transformBusinessDesc: 'Transform your Dubai business with our advanced POS system. VAT compliant, Arabic-first interface, and built specifically for UAE retail, restaurants, and service businesses.',
    noCreditCard: 'No credit card required • Setup in 5 minutes • Multi-language Support',
    advancedPOSDesc: 'Advanced POS terminals with touch screens, barcode scanning, and receipt printing',
    mobileAppDesc: 'Mobile app for inventory management, sales tracking, and customer engagement',
    instantProcessingDesc: 'Lightning-fast transaction processing with offline capability',
    whyChooseDSR: 'Why Choose DSR Info?',
    builtForUAE: 'Built specifically for UAE businesses with local expertise',
    uaeBanking: 'UAE Banking Integration',
    uaeBankingDesc: 'Direct integration with Emirates NBD, ADCB, FAB, and other local banks',
    localSupport: 'Local Support Team',
    localSupportDesc: '24/7 support in Arabic and English from our Dubai office',
    aedCurrency: 'AED Currency Support',
    aedCurrencyDesc: 'Native AED support with proper formatting and calculations',
    cloudOnPremise: 'Cloud & On-Premise',
    cloudOnPremiseDesc: 'Flexible deployment options to meet your security requirements',
    whatClientsSay: 'What Our Clients Say',
    testimonial1: '"DSR Info transformed our accounting process. VAT compliance is now effortless."',
    testimonial2: '"Excellent support team and the Arabic interface is perfect for our staff."',
    testimonial3: '"Best ERP solution we\'ve used. Saves us 10+ hours weekly on financial reporting."',
    ahmed: 'Ahmed Al Mansouri',
    ceoAlMansouri: 'CEO, Al Mansouri Trading',
    fatima: 'Fatima Hassan',
    financeManager: 'Finance Manager, Dubai Retail Co.',
    mohammad: 'Mohammad Khalil',
    ownerKhalil: 'Owner, Khalil Construction',
    readyTransform: 'Ready to Transform Your Business?',
    join500UAE: 'Join 500+ UAE businesses already using DSR Info',
    startFreeTrial: 'Start Free Trial',
    callUs: 'Call +971 4 123 4567',
    product: 'Product',
    features: 'Features',
    pricing: 'Pricing',
    support: 'Support',
    helpCenter: 'Help Center',
    contactUs: 'Contact Us',
    training: 'Training',
    contactInfo: 'Contact',
    dubaiUAE: 'Dubai, UAE',
    uaeLeadingERP: 'UAE\'s leading ERP solution for modern businesses.',
    confirmDelete: 'Are you sure you want to delete',
    actionCannotBeUndone: 'This action cannot be undone.',
  },
  ar: {
    signIn: 'تسجيل الدخول',
    startNow: 'ابدأ الآن',
    freeTrialButton: 'جرب مجاناً لمدة 30 يوم',
    watchDemo: 'شاهد العرض التوضيحي',
    advancedPOS: 'نقاط البيع المتقدمة',
    mobileApp: 'تطبيق الجوال',
    instantProcessing: 'معالجة فورية',
    copyright: '© 2026 DSR Info. جميع الحقوق محفوظة بواسطة TechRover',
    signInTitle: 'تسجيل الدخول إلى حسابك',
    signUpTitle: 'إنشاء حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    companyName: 'اسم الشركة',
    phoneNumber: 'رقم الهاتف',
    role: 'الدور',
    agent: 'وكيل',
    signingIn: 'جاري تسجيل الدخول...',
    creatingAccount: 'جاري إنشاء الحساب...',
    signUp: 'إنشاء حساب',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dashboard: 'لوحة التحكم',
    receipts: 'الإيصالات',
    payments: 'المدفوعات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
    receiptPaymentManagement: 'إدارة الإيصالات والمدفوعات',
    superAdmin: 'مدير عام',
    name: 'الاسم',
    contact: 'الاتصال',
    status: 'الحالة',
    actions: 'الإجراءات',
    active: 'نشط',
    inactive: 'غير نشط',
    overviewSystem: 'نظرة عامة على نظام إدارة الإيصالات والمدفوعات',
    totalReceiptsToday: 'إجمالي الإيصالات (اليوم)',
    totalPaymentsToday: 'إجمالي المدفوعات (اليوم)',
    pendingPayments: 'المدفوعات المعلقة',
    activeVendors: 'الوكلاء النشطين',
    monthlyOverview: 'نظرة عامة شهرية',
    recentActivity: 'النشاط الأخير',
    manageReceipts: 'إدارة جميع إدخالات الإيصالات',
    addReceipt: 'إضافة إيصال',
    searchReceipts: 'البحث في الإيصالات...',
    receiptNumber: 'رقم الإيصال',
    amount: 'المبلغ',
    date: 'التاريخ',
    vendorName: 'الوكيل',
    description: 'الوصف',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    managePayments: 'إدارة جميع معاملات الدفع',
    addPayment: 'إضافة دفعة',
    searchPayments: 'البحث في المدفوعات...',
    paymentId: 'معرف الدفع',
    batchId: 'معرف الدُفعة',
    paymentMethod: 'طريقة الدفع',
    transactionDate: 'تاريخ المعاملة',
    pending: 'معلق',
    completed: 'مكتمل',
    failed: 'فشل',
    viewReports: 'عرض التقارير والتحليلات الشاملة',
    generateReport: 'إنشاء تقرير',
    salesReport: 'تقرير المبيعات',
    paymentReport: 'تقرير المدفوعات',
    vendorReport: 'تقرير الوكلاء',
    monthlyReport: 'التقرير الشهري',
    yearlyReport: 'التقرير السنوي',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    systemSettings: 'تكوين تفضيلات النظام',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    security: 'الأمان',
    language: 'اللغة',
    theme: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    save: 'حفظ',
    cancel: 'إلغاء',
    update: 'تحديث',
    confirm: 'تأكيد',
    close: 'إغلاق',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات متاحة',
    total: 'المجموع',
    filter: 'تصفية',
    sort: 'ترتيب',
    noPaymentsFound: 'لم يتم العثور على مدفوعات',
    noPaymentsDescription: 'لم تقم بإنشاء أي مدفوعات بعد. ابدأ بإضافة أول دفعة لك.',
    addFirstPayment: 'إضافة أول دفعة',
    paymentsReport: 'تقرير المدفوعات',
    getStarted: 'ابدأ',
    settlements: 'التسويات',
    confirmDelete: 'هل أنت متأكد من أنك تريد حذف',
    actionCannotBeUndone: 'لا يمكن التراجع عن هذا الإجراء.',
  },
  hi: {
    signIn: 'साइन इन',
    startNow: 'शुरू करें',
    freeTrialButton: '30 दिन मुफ्त ट्रायल',
    watchDemo: 'डेमो देखें',
    advancedPOS: 'उन्नत POS टर्मिनल',
    mobileApp: 'मोबाइल ऐप',
    instantProcessing: 'तत्काल प्रसंस्करण',
    copyright: '© 2026 DSR Info. सभी अधिकार TechRover द्वारा सुरक्षित',
    signInTitle: 'अपने खाते में साइन इन करें',
    signUpTitle: 'अपना खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    companyName: 'कंपनी का नाम',
    phoneNumber: 'फोन नंबर',
    role: 'भूमिका',
    agent: 'एजेंट',
    signingIn: 'साइन इन हो रहा है...',
    creatingAccount: 'खाता बनाया जा रहा है...',
    signUp: 'साइन अप',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    dashboard: 'डैशबोर्ड',
    receipts: 'रसीदें',
    payments: 'भुगतान',
    reports: 'रिपोर्ट्स',
    settings: 'सेटिंग्स',
    signOut: 'साइन आउट',
    receiptPaymentManagement: 'रसीद और भुगतान प्रबंधन',
    superAdmin: 'सुपर एडमिन',
    name: 'नाम',
    contact: 'संपर्क',
    status: 'स्थिति',
    actions: 'कार्य',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    overviewSystem: 'आपकी रसीद और भुगतान प्रबंधन प्रणाली का अवलोकन',
    totalReceiptsToday: 'कुल रसीदें (आज)',
    totalPaymentsToday: 'कुल भुगतान (आज)',
    pendingPayments: 'लंबित भुगतान',
    activeVendors: 'सक्रिय एजेंट',
    monthlyOverview: 'मासिक अवलोकन',
    recentActivity: 'हाल की गतिविधि',
    manageReceipts: 'अपनी सभी रसीद प्रविष्टियों का प्रबंधन करें',
    addReceipt: 'रसीद जोड़ें',
    searchReceipts: 'रसीदें खोजें...',
    receiptNumber: 'रसीद संख्या',
    amount: 'राशि',
    date: 'दिनांक',
    vendorName: 'एजेंट',
    description: 'विवरण',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    managePayments: 'अपने सभी भुगतान लेनदेन का प्रबंधन करें',
    addPayment: 'भुगतान जोड़ें',
    searchPayments: 'भुगतान खोजें...',
    paymentId: 'भुगतान ID',
    batchId: 'बैच ID',
    paymentMethod: 'भुगतान विधि',
    transactionDate: 'लेनदेन दिनांक',
    pending: 'लंबित',
    completed: 'पूर्ण',
    failed: 'असफल',
    viewReports: 'व्यापक रिपोर्ट और विश्लेषण देखें',
    generateReport: 'रिपोर्ट जेनरेट करें',
    salesReport: 'बिक्री रिपोर्ट',
    paymentReport: 'भुगतान रिपोर्ट',
    vendorReport: 'एजेंट रिपोर्ट',
    monthlyReport: 'मासिक रिपोर्ट',
    yearlyReport: 'वार्षिक रिपोर्ट',
    exportPDF: 'PDF निर्यात करें',
    exportExcel: 'Excel निर्यात करें',
    systemSettings: 'अपनी सिस्टम प्राथमिकताएं कॉन्फ़िगर करें',
    profile: 'प्रोफाइल',
    notifications: 'सूचनाएं',
    security: 'सुरक्षा',
    language: 'भाषा',
    theme: 'थीम',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    update: 'अपडेट करें',
    confirm: 'पुष्टि करें',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    total: 'कुल',
    filter: 'फिल्टर',
    sort: 'सॉर्ट करें',
    noPaymentsFound: 'कोई भुगतान नहीं मिला',
    noPaymentsDescription: 'आपने अभी तक कोई भुगतान नहीं बनाया है। अपना पहला भुगतान जोड़कर शुरुआत करें।',
    addFirstPayment: 'पहला भुगतान जोड़ें',
    paymentsReport: 'भुगतान रिपोर्ट',
    getStarted: 'शुरू करें',
    settlements: 'सेटलमेंट्स',
    confirmDelete: 'क्या आप वाकई हटाना चाहते हैं',
    actionCannotBeUndone: 'यह क्रिया पूर्ववत नहीं की जा सकती।',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string) => {
    return (translations[language] as any)[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}